// Auto-generated by AppKit - DO NOT EDIT
// Generated by 'npx @databricks/appkit generate-types' or Vite plugin during build
import "@databricks/appkit-ui/react";
import type { SQLTypeMarker, SQLStringMarker, SQLNumberMarker, SQLBooleanMarker, SQLBinaryMarker, SQLDateMarker, SQLTimestampMarker } from "@databricks/appkit-ui/js";

declare module "@databricks/appkit-ui/react" {
  interface QueryRegistry {
    forecast_explorer: {
        name: "forecast_explorer";
        parameters: {
          /** any - use sql.*() */
          store_name: SQLTypeMarker;
          /** any - use sql.*() */
          sku: SQLTypeMarker;
        };
        result: Array<{
          /** @sqlType TIMESTAMP */
          week: string;
          /** @sqlType STRING */
          store_name: string;
          /** @sqlType STRING */
          region: string;
          /** @sqlType STRING */
          sku: string;
          /** @sqlType STRING */
          product_name: string;
          /** @sqlType STRING */
          category: string;
          /** @sqlType DOUBLE */
          actual_demand: number;
          /** @sqlType DOUBLE */
          predicted_demand: number;
          /** @sqlType DOUBLE */
          avg_demand_last_12w: number;
          /** @sqlType BOOLEAN */
          is_stockout_risk: boolean;
          /** @sqlType BOOLEAN */
          is_overstock_risk: boolean;
        }>;
      };
    forecast_explorer_options: {
        name: "forecast_explorer_options";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType STRING */
          store_name: string;
          /** @sqlType STRING */
          region: string;
          /** @sqlType STRING */
          sku: string;
          /** @sqlType STRING */
          product_name: string;
          /** @sqlType STRING */
          category: string;
        }>;
      };
    risk_dashboard: {
        name: "risk_dashboard";
        parameters: {
          /** STRING - use sql.string() */
          week: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType TIMESTAMP */
          week: string;
          /** @sqlType STRING */
          store_name: string;
          /** @sqlType STRING */
          region: string;
          /** @sqlType STRING */
          sku: string;
          /** @sqlType STRING */
          product_name: string;
          /** @sqlType STRING */
          category: string;
          /** @sqlType INT */
          predicted_demand: number;
          /** @sqlType DOUBLE */
          avg_demand_last_12w: number;
          /** @sqlType BOOLEAN */
          is_stockout_risk: boolean;
          /** @sqlType BOOLEAN */
          is_overstock_risk: boolean;
        }>;
      };
    risk_dashboard_options: {
        name: "risk_dashboard_options";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType TIMESTAMP */
          week: string;
        }>;
      };
  }
}
