// Auto-generated by AppKit - DO NOT EDIT
// Generated by 'npx @databricks/appkit generate-types' or Vite plugin during build
import "@databricks/appkit-ui/react";
import type { SQLTypeMarker, SQLStringMarker, SQLNumberMarker, SQLBooleanMarker, SQLBinaryMarker, SQLDateMarker, SQLTimestampMarker } from "@databricks/appkit-ui/js";

declare module "@databricks/appkit-ui/react" {
  interface QueryRegistry {
    risk_dashboard: {
        name: "risk_dashboard";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType STRING */
          store_name: string;
          /** @sqlType STRING */
          region: string;
          /** @sqlType STRING */
          sku: string;
          /** @sqlType STRING */
          product_name: string;
          /** @sqlType STRING */
          category: string;
          /** @sqlType BIGINT */
          predicted_demand: number;
          /** @sqlType DOUBLE */
          avg_demand_last_12w: number;
          /** @sqlType BOOLEAN */
          is_stockout_risk: boolean;
          /** @sqlType BOOLEAN */
          is_overstock_risk: boolean;
        }>;
      };
  }
}
