// Auto-generated by AppKit - DO NOT EDIT
// Generated by 'npx @databricks/appkit generate-types' or Vite plugin during build
import "@databricks/appkit-ui/react";
import type { SQLTypeMarker, SQLStringMarker, SQLNumberMarker, SQLBooleanMarker, SQLBinaryMarker, SQLDateMarker, SQLTimestampMarker } from "@databricks/appkit-ui/js";

declare module "@databricks/appkit-ui/react" {
  interface QueryRegistry {
    forecast_explorer_options: {
        name: "forecast_explorer_options";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType STRING */
          store_name: string;
          /** @sqlType STRING */
          region: string;
          /** @sqlType STRING */
          sku: string;
          /** @sqlType STRING */
          product_name: string;
          /** @sqlType STRING */
          category: string;
        }>;
      };
    forecast_explorer: {
        name: "forecast_explorer";
        parameters: { store_name: SQLStringMarker; sku: SQLStringMarker };
        result: Array<{
          /** @sqlType DATE */
          week: string;
          /** @sqlType STRING */
          store_name: string;
          /** @sqlType STRING */
          region: string;
          /** @sqlType STRING */
          sku: string;
          /** @sqlType STRING */
          product_name: string;
          /** @sqlType STRING */
          category: string;
          /** @sqlType DOUBLE */
          actual_demand: number | null;
          /** @sqlType DOUBLE */
          predicted_demand: number | null;
          /** @sqlType DOUBLE */
          avg_demand_last_12w: number | null;
          /** @sqlType BOOLEAN */
          is_stockout_risk: boolean | null;
          /** @sqlType BOOLEAN */
          is_overstock_risk: boolean | null;
        }>;
      };
    action_list: {
        name: "action_list";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType STRING */
          store_name: string;
          /** @sqlType STRING */
          region: string;
          /** @sqlType STRING */
          sku: string;
          /** @sqlType STRING */
          product_name: string;
          /** @sqlType STRING */
          category: string;
          /** @sqlType BIGINT */
          predicted_demand: number;
          /** @sqlType DOUBLE */
          avg_demand_last_12w: number;
          /** @sqlType STRING */
          risk_type: string;
          /** @sqlType DOUBLE */
          demand_delta: number;
        }>;
      };
    risk_dashboard: {
        name: "risk_dashboard";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType DATE */
          week: string;
          /** @sqlType STRING */
          store_name: string;
          /** @sqlType STRING */
          region: string;
          /** @sqlType STRING */
          sku: string;
          /** @sqlType STRING */
          product_name: string;
          /** @sqlType STRING */
          category: string;
          /** @sqlType BIGINT */
          predicted_demand: number;
          /** @sqlType DOUBLE */
          avg_demand_last_12w: number;
          /** @sqlType BOOLEAN */
          is_stockout_risk: boolean;
          /** @sqlType BOOLEAN */
          is_overstock_risk: boolean;
        }>;
      };
  }
}
